### ISSUE TITLE
The app resources are un-bounded

### ISSUE THREAD

**Issue by sbose78** [nodeshift-starters/nodejs-rest-http-crud-redhat#53]
Is it fine if we fix the resource limits for this booster to something like

```
         resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
```
